Develop (#1)
* rm README

* chore: Add simple Makefile #1

* chore: Add MLX42 #1

* chore: Add MLX42 build #1

* chore: Add libft library #1

* chore: Change submodule to static source #1

chore: Remove submodule

* chore: Add gitignore in c #1

* Parse (#4)

* chore: Ignroe MLX42 build directory #1

* chore: Fix FLAGS with MLX42 and libft #1

* resource: Add minimalist.rt for test #3

* feat: Add form for parsing #3

* style: Rename Element variables #3

* chore: Add .vscode in .gitignore #1

* feat: Parse rgb #3

* feat: Add vector4 parsing #3

* feat: Add libcustom library #3

* chore: Fix Makefile dependency #1

* fix: Fix ft_strtof function #3

* fix: Add end char '\r' for WSL & vector checker

* feat: Parse each element object #3

* feat: Add element debug #3

* fix: Parse multiple line #3

* fix: multiple line #3

* feat: Add detailed error message

* fix: Add "\n" in next_rgb

Co-authored-by: sindy <sindydwns@naver.com>

* fix: Add "\n" in parse_rgb

Co-authored-by: sindy <sindydwns@naver.com>

---------

Co-authored-by: yonshin <yonshin@student.42seoul.kr>
Co-authored-by: sindy <sindydwns@naver.com>

* chore: update gitignore

* chore: print detailed error in debug mode only

* Parse (#8)

* feat: Add ft_strarr_free for ft_split

* refactor: use singleton pattern in parse #3

* refactor: do not malloc parse in Element/*/*.c

* feat: Add sub_errno at ft_error for debug

* fix: float parse #6

* fix: errno starts with 0 #9

- In the terminal environment, errno is initialized to 0.
- In the vscode(m1 mac) environment, errno is initialized to 1.
- In the vscode(intel mac) environment, errno is initialized to 3.

* Parse #10 (#11)

* feat: Add ft_strarr_free for ft_split

* refactor: use singleton pattern in parse #3

* refactor: do not malloc parse in Element/*/*.c

* feat: Add sub_errno at ft_error for debug

* fix: float parse #6

* fix: errno starts with 0 #9

- In the terminal environment, errno is initialized to 0.
- In the vscode(m1 mac) environment, errno is initialized to 1.
- In the vscode(intel mac) environment, errno is initialized to 3.

* fix: float parse #6 #10

* Window (#12)

* feature: control window (#7)

* rename: hook -> simulate (#7)

* feature: apply feedback (#7)

Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

Update src/simulate/hook_close_event.c

Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

Update src/simulate/hook_resize_event.c

Co-authored-by: minjungk <55140902+iijung@users.noreply.github.com>

* rename: scene -> elements

* rename: scene -> elements

* chore: Fix MAKEFLAGS

because...
```
make  -- DEBUG=1 -C external fclean
make[1]: Entering directory '/mnt/c/workspace/minirt'
make[1]: *** No rule to make target '-C'.  Stop.
make[1]: Leaving directory '/mnt/c/workspace/minirt'
make: *** [Makefile:30: fclean] Error 2
```

* test: Add parse_test data #3

```
./tool/parse_test.sh
```

* Refactory (#13)

* refactory: remove libgui & add simulate.c

* refactory: hide element into parse

* Refactory (#14)

* refactory: remove libgui & add simulate.c

* refactory: hide element into parse

* norm:

---------

Co-authored-by: sindydwns <sindydwns@naver.com>

* Refactory/object oriented (#15)

* refactory: rename parse function & struct

* refactory: call functions in object type order

* refactory: formatting with norm

* Refactory/vector (#16)

* refactory: add libvector

* refactory: apply libvector to project

* Refactor (#17)

* norm: -Wall -Wextra -Werror in libvector

* refactor: malloc -> ft_calloc

초기화 되지 않은 변수는 오류가 발생하기 쉬움

권장사항 1안) malloc & memset
권장사항 2안) ft_calloc

* refactor: combine element & object

* refactor: merge parse & element

* remove: about object

* rename: parse -> import file .rt

* rename: element function name

* rename: element parse function file name

* feat: Add handler template

* feat: add element struct

---------

Co-authored-by: sindydwns <sindydwns@naver.com>

* feat: Add mandantory (#19)

* refactory: element raw data to obj data (#20)

* feat: camera fov (#22)

* Refactor/import file (#24)

* chore: implicit conversion build error

```
simulate/hook_draw.c:73:40: error: implicit conversion from 'int' to 'float' changes value from 99999999 to 1.0E+8 [-Werror,-Wimplicit-const-int-float-conversion]
        if (hit(world, ray, (t_range){ DELTA, BIGVALUE }, &rec)) {
                                     ~        ^~~~~~~~
simulate/hook_draw.c:15:18: note: expanded from macro 'BIGVALUE'
                 ^~~~~~~~
1 error generated.
```

* refactor: Move debug functions

* refactor: move parse function to file directory

* refactor: about struct s_world

* refactor: Wimplicit-const-int-float-conversion

* refactor: delete float to float casting

---------

Co-authored-by: sindydwns <sindydwns@naver.com>

* Refactor/hit (#26)

* Refactor/element (#27)

* refactor: use element base and rename self

* norm:

* Fix/camera angle (#28)

* add: rotate axis function

* fix: camera angle

* fix: camera fov (#29)

* feat: rotate camera with mouse

* fix: hit cylinder bug (#31)

* Refactor/element type (#32)

* Feat/v3 hadamard prod (#33)

* feat: add v3_hadamard_prod.c

* refactor: norm

* Feature/camera (#35)

* feat: rotate camera with mouse

* fix: static world axis up view

* fix: Fix conflict and  build error

* fix: new version camera rotation!

* data: new test file for check coordinate

* fix: Fix poor mouse conrtol for rotate

* Fix/poor control (#36)

* refactor: rename vector prod function names

* fix: rotate camera bug aka. 1,0,1 -> 0,1,0

* refactor: define world axis

* fix: camera front not defined

* fix: poor move control

* fix: resize segment fault #21 (#37)

* feat: check normalized vector3 in parse (#38)

* feat: check normalized vector3 in parse

- Fix double print errno message

* fix: typo

* Refactor/hook draw (#39)

* refactor: add color_to_pixel function

* refactor: draw hit

* refactor: classfy hook_draw_setting

* refactor: redefine WORLD_AXIS to world->axis

* refactor: norm

* refactor: replace debug functions (#40)

* feat: float to str (#41)

* feature: add libstr (#42)

* MLX42 -> Minilibx (#44)

* chore: replace mlx42 to minilibx

* rm: remove about resize

* chore: change mlx42 to minilibx

* chore: add minlibx-linux

* chore: fix minilibx relink

* chore: typo

* add .gitignore

* Feat/transform (#45)

* feat: transform

* world screen

* feat: separated drawing (#46)

* fix: Fix unmatched keycode and rename keycode

- ex. KOBOARD_W -> KEYBOARD_w

* fix: world bzero

* asdf

* refactor: fix norm and refactor for put_string

* refactor: norm

* refactor: set_pixel

* chore: remove unused macro values

* fix: dismatch selection

* refactor: motion notify hook -> mlx_mouse_get_pos

* style: rename mouse.prev -> mouse.press

* feat: transform objects with mouse

* chore: fix cross compile for get_mouse_pos

* chore: update get_mouse_pos for mac version

* Refactor/mandatory (#48)

* refactor: get_camera_ray

* refactor: add function v3_preset

* refactor: add function rgb_to_color

* refactor: ray_color

* refactor: add function render_main_frame

* feat: antialiasing

* refactor: rm unsed lib/libstr

* fix: float -> double

* refactor: mouse hook

* refactor: add define value - separate

* refactor: rename render_mode -> render_text

* chore: update gitignore

* refactor: simulate - dont fail hook setting

* fix: makefile fclean error

* feat: light movement

* refactor: remove useless q e button

* feat: render type_name

* refactor: reduce code size

* Refactor/viewport (#49)

* refactor: add function render_main_frame

* refactor: rename render_mode -> render_text

* refactor: rename gui_setting -> viewport

* norm: rename viewport.screen -> viewport.size

* refactor: rename hook_close_event -> destroy_notify

* refactor: use viewport in hook (world -> viewport)

* refactor: classify viewport source code

* refactor: classify controller and hook

* refactor: move to viewport about hook_event

* refactor: const static g_keycode must in .c

* refactor: remove hook header

* refactor: combine controller with hook_draw

* refactor: rename viewport -> workspace

* Revert "refactor: rename viewport -> workspace"

This reverts commit 4d5707bad809c6c28aba4c90264844df17178f6d.

* refactor: rename struct viewport -> device

* temp

* norm:

---------

Co-authored-by: yonshin <yonshin@student.42seoul.kr>

* refactor: move device functions (#50)

* refactor: move device functions

* mlx + win = device

* set_pixel -> put_pixel

* Chore/bonus (#51)

* chore: clean object and dependency file with find command

* chore: make mandatory and bonus

* miss file (#52)

* front up right (#54)

* Feat/bonus checkerboard (#56)

* feat: plane checkerboard (with norm error)

* feat: sphere checkerboard (with norm)

* feat: cylinder checkerboard (without norm)

* fix: checkerboard color

* fix: cylinder top-body-bottom continuous checkerboard

* refactor: asdf -> uv_ratio

* refactor: change 'method for get element color'

refactor: define cylinder hit status

refactor: add function hit_color

refactor: remove hit_bonus, add hit_color_bonus

* fix: cylinder checkerboard bug fix (with norm)

* Feature/specular (#55)

* fix: diffuse light

* feat: specular

* feat: set render_mode for debug

* feat: render with mode

f1: original (100%)
f2: ambient (100%)
f3: diffuse (50%)
f4: specular (50%)

* debug: for debugging render_mode

* refactor: classify multi-light function

* feat: render_mode specular

* feat: graphical render mode

---------

Co-authored-by: sindydwns <sindydwns@naver.com>

* Refactor/header (#61)

* refactor: remove simulate_util

* refacotr: remove simulate.c

* refactor: rename simulate.h -> miniRT.h

* refactor: relocate simulate/draw/ -> draw/

* refactor: remove simulate function

* refactor: split file device.c -> create_device.c, destroy_device.c

* refactor: draw/hook_draw.c -> main_loop.c

* refactor: add file_private.h

* refactor: move e_vector_scope. common.h -> file_private.h

* refactor: move parse_vector3, parse_rgb

* refactor: type t_hit->elem void *

* refactor: rename common.h -> element.h

---------

Co-authored-by: sindydwns <sindydwns@naver.com>

* Refactor/rgb only access file (#64)

* refactor: add common.h

* refactor: struct rgb only access file module

* fix: set default rgb when argv[2] is null for parse light

* refactor: remove element obj

* fix: add color bright #60 (#65)

* fix: add color bright #60

* fix: ambient

* fix: add brighntess

* fix: ambient once

* chore: for multi-light

* norm: import_file_bonus

* Feat/bonus bump map (#66)

* chore: add wall xpm file

* refactor: split file for bumpmap

* feat: bumpmap

norm & parse

* chore: bumpmap data

* Refactor (#67)

* refactor: remove delta in get_camera_ray

- delta is unnecessary value

* refactor: remove t_ray in render

* refactor: unncessary max_len range

* refactor: reduce element_* header dependency

- if add cone, you can just modify Element/Cone and element_iter

* refactor: move util transform structure

* refactor: rename update and render

* refactor: global dto in import_file

* refactor: ray structure in common.h -> element_util

* refactor: draw/get_camera_ray -> Element/util/

* refactor: draw/hit -> Element/hit

* refactor: rename common.c -> element_iter.c

* fix: uninitialized value

$ valgrind --track-origins=yes ./miniRT ../data/coordination.rt
==13609== Memcheck, a memory error detector
==13609== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13609== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==13609== Command: ./miniRT ../data/coordination.rt
==13609==
==13609== Conditional jump or move depends on uninitialised value(s)
==13609==    at 0x487682C: sqrt (w_sqrt_compat.c:35)
==13609==    by 0x111238: v3_magnitude (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x111275: v3_normalize (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10D400: parse_light (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10C7C2: import_file (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10A5C7: main (in /home/iijung/minirt/src/miniRT)
==13609==  Uninitialised value was created by a stack allocation
==13609==    at 0x10D22D: parse_light (in /home/iijung/minirt/src/miniRT)
==13609==
==13609== Conditional jump or move depends on uninitialised value(s)
==13609==    at 0x111287: v3_normalize (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10D400: parse_light (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10C7C2: import_file (in /home/iijung/minirt/src/miniRT)
==13609==    by 0x10A5C7: main (in /home/iijung/minirt/src/miniRT)
==13609==  Uninitialised value was created by a stack allocation
==13609==    at 0x10D22D: parse_light (in /home/iijung/minirt/src/miniRT)
==13609==
Xlib:  extension "MIT-SHM" missing on display "172.17.144.1:0".
==13609==
==13609== HEAP SUMMARY:
==13609==     in use at exit: 3,420,038 bytes in 119 blocks
==13609==   total heap usage: 312 allocs, 193 frees, 3,434,338 bytes allocated
==13609==
==13609== LEAK SUMMARY:
==13609==    definitely lost: 0 bytes in 0 blocks
==13609==    indirectly lost: 0 bytes in 0 blocks
==13609==      possibly lost: 0 bytes in 0 blocks
==13609==    still reachable: 3,420,038 bytes in 119 blocks
==13609==         suppressed: 0 bytes in 0 blocks
==13609== Rerun with --leak-check=full to see details of leaked memory
==13609==
==13609== For lists of detected and suppressed errors, rerun with: -s
==13609== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 1 from 1)

* fix: warning message

* feat: add new element cone (#69)

* feat: add new element cone

* refactor: cylinder alias x (#70)

* chore: remove unimplemented prototype (#71)

* Feat/thread rendering (#72)

* feat: thread rendering

* feat: +antialiasing - high quality low frame

* feat: remove antialiasing from mandatory

* Revert "Feat/thread rendering (#72)"

This reverts commit e200557e6d8bfc4132396517faf3be311a168008.

* fix: segv

* data: for bonus test

* docs: add README.md

---------

Co-authored-by: yonshin <yonshin@student.42seoul.kr>
Co-authored-by: sindy <sindydwns@naver.com>